[workspace]
default-members = ["ldhcpd"]

members = ["ldhcpd"]

[workspace.package]
authors = ["Lance Hart <me@lancehart.ca>"]
edition = "2021"
repository = "https://github.com/shipsimfan/ldhcp"
license = "GPL-3.0-or-later"
publish = false
